### ISSUE TITLE
Tested the script

### ISSUE THREAD

**Issue by JensvandeWiel** [Ferks-FK/ControlPanel.gg-Installer#4]
I want this script real bad but i found some issues:
- [https://imgur.com/a/PAMxYsU](url) (database password variable)
- [https://imgur.com/a/LxSurwe](url) (lets encrypt does weird)
I know you did not update it for a long time so just some things i found if i knew bash i would pull and fix and let you update but my knowledge is small

**Comment by Ferks-FK** [comment]
The script is broken, I plan to review and fix it at some point.
