### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dgcardoso** [Ferks-FK/ControlPanel.gg-Installer#5]
Tem um erro logo apos o ID user do pterodactyl, em seguida pede a senha, coloquei porém o mesmo diz um erro e logo após fala que instalo tudo. porém ao acessar login não entra.

**Comment by wildmaster84** [comment]
> ‎It has an error right after the user ID of pterodactyl, then asks for the password, I put but the same says an error and soon after saying that I install everything. but when accessing login does not enter.‎

Sounds like you installed MySQL, I have ran into this issue with many projects while MySQL was installed and i fixed it by installing MariaDB.

MariaDB:
`sudo apt update`
`sudo apt install mariadb-server`
`sudo mysql_secure_installation`

**Comment by Ferks-FK** [comment]
> Tem um erro logo apos o ID user do pterodactyl, em seguida pede a senha, coloquei porém o mesmo diz um erro e logo após fala que instalo tudo. porém ao acessar login não entra.

Este script está defazado, não faça o uso do mesmo.
Estarei atualizando assim que possível.

**Comment by dgcardoso** [comment]
ok, obrigado!

**Comment by wildmaster84** [comment]
> > Tem um erro logo apos o ID user do pterodactyl, em seguida pede a senha, coloquei porém o mesmo diz um erro e logo após fala que instalo tudo. porém ao acessar login não entra.
> 
> Este script está defazado, não faça o uso do mesmo. Estarei atualizando assim que possível.

When should we expect an update to the script?

**Comment by Ferks-FK** [comment]
> When should we expect an update to the script?

I have no idea, but this may take some time.
